services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./homeassistant:/config
      - /var/run/dbus:/var/run/dbus:ro
      - /run/udev:/run/udev:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./homeassistant/mosquitto/config:/mosquitto/config
      - ./homeassistant/mosquitto/data:/mosquitto/data
      - ./homeassistant/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
    restart: unless-stopped

  bridge:
    build: ./bridge
    container_name: bridge
    environment:
      - MQTT_BROKER=mosquitto
    depends_on:
      - mosquitto
    restart: unless-stopped
    privileged: true
    volumes:
      - ./homeassistant/secrets.yaml:/app/secrets.yaml:ro
      - /var/run/dbus:/var/run/dbus:ro
      - /run/udev:/run/udev:ro
