- id: 'bedroom_lights_on_830pm'
  alias: 'Bedroom Lights On at 8:30 PM'
  description: 'Turns the bedroom lights on to their default state at 8:30 PM.'
  trigger:
    - platform: time
      at: "20:30:00"
  action:
    - service: light.turn_on
      target:
        entity_id: light.bedroom_lights
  mode: single

- id: 'bedroom_lights_off_1230am'
  alias: 'Bedroom Lights Off at 12:30 AM'
  description: 'Turns the bedroom lights off at 12:30 AM daily.'
  trigger:
    - platform: time
      at: "00:30:00"
  action:
    - service: light.turn_off
      target:
        entity_id: light.bedroom_lights
  mode: single

- id: 'bedroom_fade_script_on'
  alias: 'Turn On Bedroom Fade'
  description: 'Starts the rainbow fade script.'
  trigger: [] # Trigger for manual/voice control
  action:
    - service: script.turn_on
      target:
        entity_id: script.bedroom_rainbow_fade
  mode: single

- id: 'bedroom_fade_script_off'
  alias: 'Turn Off Bedroom Fade'
  description: 'Stops the rainbow fade script.'
  trigger: [] # For manual/voice control
  action:
    - service: script.turn_off
      target:
        entity_id: script.bedroom_rainbow_fade
  mode: single
