# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

light:
  - platform: cozylife
    lights:
      - ip: 192.168.12.226
        did: "69368867cb94c4f2dc9"
        pid: "enbCcn"
        dmn: "Cozy Bulb"
        dpid: [1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 14, 15, 44]

  # Creates a single entity to control both lights
  - platform: group
    name: "Bedroom Lights"
    unique_id: "bedroom_lights_group_001"
    entities:
      - light.cozylife_2dc9
      - light.bedframe_led_light

mqtt:
  light:
    - name: "Bedframe LED Light"
      unique_id: "bedframe_led_001"
      schema: json
      state_topic: "bedframe/light/state"
      command_topic: "bedframe/light/set"
      availability_topic: "bedframe/light/availability"
      payload_available: "online"
      payload_not_available: "offline"
      supported_color_modes: ["rgb"]
      brightness: true
      optimistic: false
