services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant-stack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./config:/config:rw
    restart: always
    network_mode: host

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    ports:
      - "1883:1883"
    restart: always

  bridge:
    build: ../bridge
    container_name: bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    depends_on:
      - mosquitto
    restart: always
