name: CI Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository & Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Tools & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          # Install bridge dependencies from the root, pointing to the file
          pip install -r ./bridge/requirements.txt

      - name: Lint and Format Check
        # Run checks against the bridge directory from the root
        run: |
          flake8 ./bridge
          black --check ./bridge

      - name: Build Docker Containers
        # Run the build from the root where the compose file is
        run: docker compose build
