name: CI Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          pip install -r bridge/requirements.txt

      - name: Lint and Format Check
        run: |
          flake8 bridge/ --count --select=E9,F63,F7,F82 --show-source --statistics
          black bridge/ --check

      - name: Build Docker Containers
        working-directory: ./homeassistant
        run: |
          echo "PUID=1000" > .env
          echo "PGID=1000" >> .env
          docker compose build
